name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas

  workflow_dispatch:

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5


